Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.provision :shell, path: "bootstrap.sh"
    config.vm.network :private_network, ip: "10.0.0.10"
  end

  config.vm.define "test1" do |test1|
    test1.vm.hostname = "test1"
    config.vm.network :private_network, ip: "10.0.0.11"
  end
end